export const DealsSeed = [
  {
    deleted: false,
    deletedOn: null,
    deletedBy: null,
    createdOn: "2022-04-10T09:07:48.715Z",
    id: 21,
    name: "daily grocery",
    img: "/images/deals1.jpg",
    description: " ",
    dailyFeatured: false,
    setDate: false,
    startDate: null,
    endDate: null,
    setDiscount: true,
    discountType: "percent",
    discountValue: 5,
    isActive: true,
    bannerId: null,
  },
  {
    deleted: false,
    deletedOn: null,
    deletedBy: null,
    createdOn: "2022-04-10T09:07:48.715Z",
    id: 21,
    name: "daily grocery",
    img: "/images/deals3.jpg",
    description: " ",
    dailyFeatured: false,
    setDate: false,
    startDate: null,
    endDate: null,
    setDiscount: true,
    discountType: "percent",
    discountValue: 5,
    isActive: true,
    bannerId: null,
  },
  {
    deleted: false,
    deletedOn: null,
    deletedBy: null,
    createdOn: "2022-04-26T09:35:39.039Z",
    img: "/images/deals2.jpg",
    id: 22,
    name: "FAST DELIVERY",
    description: "EVERY ORDER DELIVERY WITHIN 24 HOUR",
    dailyFeatured: true,
    setDate: false,
    startDate: null,
    endDate: null,
    setDiscount: false,
    discountType: null,
    discountValue: null,
    isActive: true,
    bannerId: null,
  },
];
